// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
	mock "github.com/stretchr/testify/mock"
)

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

// Exec provides a mock function with given fields: ctx, sql, args
func (_m *MockQuerier) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	var_args := []interface{}{ctx, sql}
	for _, a := range args {
		var_args = append(var_args, a)
	}
	ret := _m.Called(var_args...)

	var r0 pgconn.CommandTag
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) pgconn.CommandTag); ok {
		r0 = rf(ctx, sql, args...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(ctx, sql, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Query provides a mock function with given fields: ctx, sql, args
func (_m *MockQuerier) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	var_args := []interface{}{ctx, sql}
	for _, a := range args {
		var_args = append(var_args, a)
	}
	ret := _m.Called(var_args...)

	var r0 pgx.Rows
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) pgx.Rows); ok {
		r0 = rf(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Rows)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(ctx, sql, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryRow provides a mock function with given fields: ctx, sql, args
func (_m *MockQuerier) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	var_args := []interface{}{ctx, sql}
	for _, a := range args {
		var_args = append(var_args, a)
	}
	ret := _m.Called(var_args...)

	var r0 pgx.Row
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) pgx.Row); ok {
		r0 = rf(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Row)
		}
	}

	return r0
}
