// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockRow is an autogenerated mock type for the Row type
type MockRow struct {
	mock.Mock
}

// Scan provides a mock function with given fields: dest
func (_m *MockRow) Scan(dest ...any) error {
	var_args := []interface{}{}
	for _, a := range dest {
		var_args = append(var_args, a)
	}
	ret := _m.Called(var_args...)

	var r0 error
	if rf, ok := ret.Get(0).(func(...any) error); ok {
		r0 = rf(dest...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
